functionality:
  name: base_python
  description: A Python 3.10 with anndata preinstalled.
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        packages:
          - anndata~=0.8.0
          - scanpy
          - pyyaml
          - requests
          - jsonschema
