name: "fetch_task_run"
namespace: "project"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "string"
    name: "--input"
    description: "The S3 path to the task execution directory to fetch."
    info: null
    example:
    - "s3://openproblems-nextflow/work/f6/8565066aee4771cc2790b92b4ac660"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    description: "Output directory containing the fetched task execution files."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
description: "Fetches a task execution directory from an S3 bucket and sync the input\
  \ data."
info: null
status: "enabled"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/core"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
engines:
- type: "docker"
  id: "docker"
  image: "amazon/aws-cli:latest"
  namespace_separator: "/"
  entrypoint: []
  cmd: null
build_info:
  config: "src/project/fetch_task_run/config.vsh.yaml"
  runner: "executable"
  engine: "docker"
  output: "target/executable/project/fetch_task_run"
  executable: "target/executable/project/fetch_task_run/fetch_task_run"
  viash_version: "0.9.0"
  git_commit: "405c288a53c9a011b41688a47a84c249aa7ba586"
  git_remote: "https://github.com/openproblems-bio/core"
package_config:
  name: "core"
  version: "build_main"
  description: "Core components for the OpenProblems project.\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/pancreas"
      dest: "resources_test/common/pancreas"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  keywords:
  - "openproblems"
  - "common-resources"
  - "single-cell"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/core"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/core/issues"
