name: base_pytorch_nvidia
description: An nvcr.io pytorch 24.06-py3 with anndata preinstalled.
test_resources:
  - type: python_script
    path: test_pytorch.py
  - type: python_script
    path: ../python/test_anndata.py
engines:
  - type: docker
    image: nvcr.io/nvidia/pytorch:24.06-py3
    setup:
      - type: apt
        packages:
          - procps
          - git
      - type: python
        packages:
          - anndata~=0.11.0
          - scanpy~=1.11.0
          - pyyaml
          - requests
          - jsonschema
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems
