name: pytorch_nvidia
description: An nvcr.io pytorch 24.06-py3 with anndata preinstalled.
engines:
  - type: docker
    image: nvcr.io/nvidia/pytorch:24.06-py3
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        packages:
          - anndata~=0.10.0
          - scanpy~=1.10.0
          - pyyaml
          - requests
          - jsonschema
