name: "sync_resources"
namespace: "common"
description: Synchronise the resources from s3 to resources_test
usage: |
  sync_resources
  sync_resources --input _viash.yaml --output resources_test
arguments:
  - name: "--input"
    alternatives: ["-i"]
    type: file
    description: "Path _viash.yaml file with s3 path to resources."
    default: _viash.yaml
  - name: "--output"
    alternatives: ["-o"]
    type: file
    default: /resources_test
    direction: output
    description: "Path to the test resource directory."
  - name: "--quiet"
    type: boolean_true
    description: "Displays the operations that would be performed using the specified command without actually running them."
  - name: "--dryrun"
    type: boolean_true
    description: "Does not display the operations performed from the specified command."
  - name: "--delete"
    type: boolean_true
    description: "Files that exist in the destination but not in the source are deleted during sync."
  - name: "--exclude"
    type: "string"
    multiple: true
    description: Exclude all files or objects from the command that matches the specified pattern.
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: run_test.sh
engines:
  - type: docker
    image: "amazon/aws-cli:2.17.11"
    setup:
      - type: yum
        packages: [wget]
      - type: docker
        run : |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && \
          chmod +x /usr/bin/yq
runners:
  - type: executable
  - type: nextflow
