render_task_readme_qmd <- function(task_metadata) {
  cli::cli_inform("Render authors")
  authors_str <- .render_task_authors(task_metadata)

  cli::cli_inform("Render task graph")
  task_graph <- .render_task_graph(task_metadata)

  cli::cli_inform("Render task API parts")
  task_api_parts <- .render_task_parts(task_metadata)

  # TODO: add link to source
  # relative_path <- par[["task_dir"]] %>%
  #   gsub(paste0(dirname(par[["viash_yaml"]]), "/*"), "", .) %>%
  #   gsub("/*$", "", .)
  # source_url <- paste0(viash_info$links$repository, "/", relative_path)

  qmd_content <- openproblems::strip_margin(glue::glue("
    §---
    §title: \"{viash_info$label}\"
    §format: gfm
    §---
    §
    §<!--
    §This file is automatically generated from the tasks's api/*.yaml files.
    §Do not edit this file directly.
    §-->
    §
    §{viash_info$summary}
    §
    §Path to source: [`{relative_path}`]({source_url})
    §
    §{readme_str}
    §
    §## Description
    §
    §{viash_info$description}
    §{authors_str}
    §## API
    §
    §{task_graph}
    §
    §{paste(task_api_parts, collapse = '\n\n')}
    §
    §"), symbol = "§")
}

#' @importFrom openproblems.utils list_as_tibble
.render_task_authors <- function(task_metadata) {
  if (length(task_metadata$authors) == 0) {
    return("")
  }

  authors_df <- map_df(task_metadata$authors, function(aut) {
    aut$roles <- paste(aut$roles, collapse = ", ")
    list_as_tibble(aut)
  })

  paste0(
    "\n## Authors & contributors\n\n",
    authors_df %>% knitr::kable() %>% paste(collapse = "\n"),
    "\n"
  )
}

.render_task_graph <- function(task_metadata) {
  graph <- task_metadata$task_graph
  order <- task_metadata$task_graph_order

  vdf <- igraph::as_data_frame(graph, "vertices") %>%
    arrange(match(.data$name, order))
  edf <- igraph::as_data_frame(graph, "edges") %>%
    arrange(match(.data$from, order), match(.data$to, order))

  openproblems::strip_margin(glue::glue("
    |```mermaid
    |flowchart LR
    |{paste(vdf$str, collapse = '\n')}
    |{paste(edf$str, collapse = '\n')}
    |```
    |"), symbol = "\\|")
}

.render_task_parts <- function(task_metadata) {
  order <- task_metadata$task_graph_order

  map_chr(
    order,
    function(...) { # TODO
      if (task_metadata$comp_info[[file_name]]) {
        render_component(task_metadata$comp_info[[file_name]])
      } else {
        render_file(task_metadata$file_info[[file_name]])
      }
    }
  )
}
