functionality:
  name: base_r
  description: An R2U 22.04 with anndata preinstalled.
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: apt
        packages:
          - procps
          - libhdf5-dev
          - libgeos-dev
          - python3
          - python3-pip
          - python3-dev
          - python-is-python3
      - type: python
        packages:
          - rpy2
          - anndata~=0.8.0
          - scanpy
          - pyyaml
          - requests
          - jsonschema
      - type: r
        packages:
          - anndata
          - BiocManager
          - bit64
        github:
          - rstudio/reticulate
