name: base_r
description: An R2U 22.04 image with anndata preinstalled.
test_resources:
  # check whether anndata is correctly installed
  - type: r_script
    path: test.R
    text: |
      library(anndata)
      adata <- AnnData(
        X = matrix(rnorm(100), nrow = 10),
        obs = data.frame(
          cell_type = factor(rep(c("A", "B"), each = 5))
        )
      )
      print(adata)
      print("Test passed")
engines:
  - type: docker
    image: rocker/r2u:22.04
    setup:
      - type: apt
        packages:
          - git
          - procps
          - libhdf5-dev
          - libgeos-dev
          - python3
          - python3-pip
          - python3-dev
          - python-is-python3
      - type: python
        packages:
          - rpy2
          - anndata~=0.10.0
          - scanpy~=1.10.0
          - pyyaml
          - requests
          - jsonschema
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems
      - type: r
        packages:
          - anndata
          - BiocManager
          - reticulate
          - bit64
        github:
          - openproblems-bio/core/packages/r/openproblems
