name: base_r
description: An R2U 22.04 image with anndata preinstalled.
test_resources:
  - type: r_script
    path: test_anndatar.R
  - type: python_script
    path: ../python/test_anndata.py
engines:
  - type: docker
    image: rocker/r2u:24.04
    setup:
      - type: docker
        env: 
          - PIP_BREAK_SYSTEM_PACKAGES=1
          - RETICULATE_PYTHON=/usr/bin/python
      - type: apt
        packages:
          - git
          - procps
          - libhdf5-dev
          - libgeos-dev
          - python3-pip
          - python3-dev
          - python-is-python3
      - type: python
        user: true
        packages:
          - rpy2
          - anndata~=0.11.0
          - scanpy~=1.11.0
          - pyyaml
          - requests
          - jsonschema
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems
      - type: r
        packages:
          - anndata
          - BiocManager
          - reticulate
          - bit64
          - rhdf5
        github:
          - openproblems-bio/core/packages/r/openproblems
          - scverse/anndataR@0.99.0
    test_setup:
      - type: r
        packages:
          - testthat
