name: base_python
description: A Python 3.12 image with anndata preinstalled.
test_resources:
  - type: python_script
    path: test_anndata.py
engines:
  - type: docker
    image: python:3.11
    setup:
      - type: apt
        packages:
          - procps
          - git
      - type: python
        packages:
          - anndata~=0.11.0
          - scanpy~=1.11.0
          - pyyaml
          - requests
          - jsonschema
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems