from __future__ import annotations
import re


def render_task_readme_qmd(
    task_metadata: dict | str, add_instructions: bool = False
) -> str:
    """Render the ``README.qmd`` for a task.

    Args:
        task_metadata: Either a path to the task/API directory or a metadata
            dict returned by :func:`read_task_metadata`.
        add_instructions: When ``True``, prepend installation and usage
            instructions (off by default).

    Returns:
        A Quarto markdown string suitable for writing to ``README.qmd``.
    """
    if isinstance(task_metadata, str):
        from .read_task_metadata import read_task_metadata

        task_metadata = read_task_metadata(task_metadata)

    proj_conf = task_metadata["proj_conf"]
    label = proj_conf.get("label", "")
    summary = (proj_conf.get("summary") or "").strip()
    description = (proj_conf.get("description") or "").strip()

    repository_url = (proj_conf.get("links") or {}).get("repository", "")
    repo_match = re.search(r"https://github\.com/([^/]+/[^/]+)", repository_url)
    repository_name = repo_match.group(1) if repo_match else repository_url

    authors_str = _render_authors(task_metadata)
    task_graph = _render_task_graph(task_metadata)
    task_api_parts = _render_task_parts(task_metadata)
    instructions = _render_instructions(task_metadata) if add_instructions else ""

    lines = [
        "---",
        f'title: "{label}"',
        "format: gfm",
        "---",
        "",
        "<!--",
        "This file is automatically generated from the tasks's api/*.yaml files.",
        "Do not edit this file directly.",
        "-->",
        "",
        summary,
        "",
        f"Repository: [{repository_name}]({repository_url})",
        "",
    ]

    if instructions:
        lines += [instructions, ""]

    lines += [
        "## Description",
        "",
        description,
        "",
        authors_str,
        "",
        "## API",
        "",
        task_graph,
        "",
        "\n\n".join(task_api_parts),
    ]

    return "\n".join(lines)


def _render_authors(task_metadata: dict) -> str:
    from ._markdown import format_markdown_table

    authors = task_metadata["proj_conf"].get("authors") or []
    if not authors:
        return ""

    # Collect columns: name, roles, then any info keys
    all_keys: list[str] = ["name", "roles"]
    for aut in authors:
        for key in aut.get("info") or {}:
            if key not in all_keys:
                all_keys.append(key)

    rows = []
    for aut in authors:
        info = aut.get("info") or {}
        roles = aut.get("roles") or []
        roles_str = ", ".join(roles) if isinstance(roles, list) else str(roles)
        row = [aut.get("name", ""), roles_str] + [info.get(k, "") for k in all_keys[2:]]
        rows.append(row)

    headers = [k.capitalize() for k in all_keys]
    table = format_markdown_table(headers, rows)
    return "\n## Authors & contributors\n\n" + table + "\n"


def _render_task_graph(task_metadata: dict) -> str:
    G = task_metadata["task_graph"]
    order = task_metadata["task_graph_order"]
    repository_url = (task_metadata["proj_conf"].get("links") or {}).get("repository")

    def clean_id(node_id: str) -> str:
        return node_id.replace("graph", "graaf")

    def make_label(node_id: str, label: str, is_comp: bool) -> str:
        if not repository_url:
            return label
        slug = re.sub(r"[^a-z0-9]", "-", label.lower())
        anchor = f"component-type-{slug}" if is_comp else f"file-format-{slug}"
        return f"<a href='{repository_url}#{anchor}'>{label}</a>"

    node_order = {name: i for i, name in enumerate(order)}

    sorted_nodes = sorted(
        G.nodes(data=True), key=lambda x: node_order.get(x[0], len(order))
    )
    node_lines = []
    for node_id, attrs in sorted_nodes:
        label = make_label(
            node_id, attrs.get("label", node_id), attrs.get("is_comp", False)
        )
        cid = clean_id(node_id)
        if attrs.get("is_comp", False):
            node_lines.append(f'  {cid}[/"{label}"/]')
        else:
            node_lines.append(f'  {cid}("{label}")')

    sorted_edges = sorted(
        G.edges(data=True),
        key=lambda e: (
            node_order.get(e[0], len(order)),
            node_order.get(e[1], len(order)),
        ),
    )
    edge_lines = []
    for from_node, to_node, attrs in sorted_edges:
        from_to = attrs.get("from_to", "comp_to_file")
        required = attrs.get("required", True)
        if from_to == "file_to_comp":
            edge_type = "---" if required else "-.-"
        else:
            edge_type = "-->" if required else ".->"
        edge_lines.append(f"  {clean_id(from_node)}{edge_type}{clean_id(to_node)}")

    return "\n".join(
        [
            "```mermaid",
            "flowchart TB",
            *node_lines,
            *edge_lines,
            "```",
        ]
    )


def _render_task_parts(task_metadata: dict) -> list[str]:
    from .render_component_spec import render_component_spec
    from .render_file_format import render_file_format

    parts = []
    for name in task_metadata["task_graph_order"]:
        if name in task_metadata["comps"]:
            parts.append(render_component_spec(task_metadata["comps"][name]))
        elif name in task_metadata["files"]:
            parts.append(render_file_format(task_metadata["files"][name]))
    return parts


def _render_instructions(task_metadata: dict) -> str:
    proj_name = task_metadata["proj_conf"].get("name", "")
    return "\n".join(
        [
            "### Installation",
            "",
            "You need to have Docker, Java, and Viash installed. Follow",
            "[these instructions](https://openproblems.bio/documentation/fundamentals/requirements)",
            "to install the required dependencies.",
            "",
            "### Add a method",
            "",
            "To add a method to the repository, follow the instructions in the `scripts/add_a_method.sh` script.",
            "",
            "### Initial setup",
            "",
            "To get started, you can run the following commands:",
            "",
            "```bash",
            f"git clone git@github.com:openproblems-bio/{proj_name}.git",
            "",
            f"cd {proj_name}",
            "",
            "# initialise submodule",
            "scripts/init_submodule.sh",
            "",
            "# download resources",
            "scripts/download_resources.sh",
            "```",
            "",
            "To run the benchmark, you first need to build the components. Afterwards, you can run the benchmark:",
            "",
            "```bash",
            "viash ns build --parallel --setup cachedbuild",
            "",
            "scripts/run_benchmark.sh",
            "```",
            "",
            "After adding a component, it is recommended to run the tests to ensure that the component is working correctly:",
            "",
            "```bash",
            "viash ns test --parallel",
            "```",
            "",
            "Optionally, you can provide the `--query` argument to test only a subset of components:",
            "",
            "```bash",
            "viash ns test --parallel --query 'component_name'",
            "```",
        ]
    )
